apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ConfigMap 
  metadata:
    name: order-config
    namespace: default
  data:
    FOO: bar
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: order
    namespace: default
  spec:
    progressDeadlineSeconds: 900
    replicas: 1
    revisionHistoryLimit: 0
    selector:
      matchLabels:
        app: order
    strategy:
      rollingUpdate:
        maxSurge: "0%"
        maxUnavailable: "25%"
      type: RollingUpdate
    template:
      metadata:
        annotations:
          cluster-autoscaler.kubernetes.io/safe-to-evict: 'false'
        labels:
          azure.workload.identity/use: "true"
          app: order
      spec:
        automountServiceAccountToken: false
        # az aks connection show --connection order_acme_postgres -g yuwzho-acme -n yuwzho-acme-k8s --query kubernetesResourceName
        serviceAccountName: sc-account-f0e94657-c797-4229-8baa-f5d3e25149fb
        containers:
        - env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          - name: APPLICATIONINSIGHTS_ROLE_NAME
            value: order
          envFrom:
          - secretRef:
              # az aks connection show --connection order_acme_postgres -g yuwzho-acme -n yuwzho-acme-k8s --query kubernetesResourceName
              name: sc-orderacmepostgres-secret
          - configMapRef:
              name: order-config
          image: acmeacr.azurecr.io/acme-order:buildpack
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 300
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 8080
            timeoutSeconds: 3
          name: order
          ports:
          - containerPort: 8080
            name: app-port
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 0
            periodSeconds: 5
            successThreshold: 1
            tcpSocket:
              port: 8080
            timeoutSeconds: 3
          resources:
            limits:
              cpu: "2"
              ephemeral-storage: "5000Mi"
              memory: "4Gi"
            requests:
              cpu: "2"
              ephemeral-storage: "5000Mi"
              memory: "4Gi"
          volumeMounts:
          - mountPath: /tmp
            name: temp
        terminationGracePeriodSeconds: 90
        volumes:
        - emptyDir:
            sizeLimit: "5Gi"
          name: temp
- apiVersion: v1
  kind: Service
  metadata:
    name: order-service
    namespace: default
  spec:
    selector:
      app: order
    ports:
      - protocol: TCP
        port: 80
        targetPort: 8080
    type: ClusterIP