apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ConfigMap 
  metadata:
    name: catalog-config
    namespace: default
  data:
    EUREKA_CLIENT_ENABLED: 'true'
    SPRING_APPLICATION_NAME: catalog
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: catalog
    namespace: default
  spec:
    progressDeadlineSeconds: 900
    replicas: 1
    revisionHistoryLimit: 0
    selector:
      matchLabels:
        app: catalog
    strategy:
      rollingUpdate:
        maxSurge: "0%"
        maxUnavailable: "25%"
      type: RollingUpdate
    template:
      metadata:
        annotations:
          cluster-autoscaler.kubernetes.io/safe-to-evict: 'false'
        labels:
          azure.workload.identity/use: "true"
          app: catalog
      spec:
        automountServiceAccountToken: false
        # az aks connection show --connection catalog_acme_postgres -g yuwzho-acme -n yuwzho-acme-k8s --query kubernetesResourceName
        serviceAccountName: sc-account-15b84cb5-44d1-41c0-ac5b-367a67b53ca0
        containers:
        - env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          - name: JAVA_OPTS
            value: -Deureka.client.service-url.defaultZone=$(SPRING_EUREKA_SERVICE_URL)
              -Dfile.encoding=UTF8 -DCONFIG_SERVER_URL=$(SPRING_CLOUD_CONFIG_URI) -Dspring.cloud.config.uri=$(SPRING_CLOUD_CONFIG_URI)
              -Dspring.cloud.config.fail-fast=$(SPRING_CLOUD_CONFIG_FAILFAST) -Dspring.config.import=optional:configserver:$(SPRING_CLOUD_CONFIG_URI)/
          - name: SERVER_PORT
            value: '8080'
          - name: APPLICATIONINSIGHTS_ROLE_NAME
            value: catalog
          envFrom:
          - secretRef:
              # az aks connection show --connection catalog_acme_postgres -g yuwzho-acme -n yuwzho-acme-k8s --query kubernetesResourceName
              name: sc-catalogacmepostgres-secret
          - configMapRef:
              name: config-server-config
              optional: true
          - configMapRef:
              name: eureka-server-config
              optional: true
          - configMapRef:
              name: catalog-config
          image: acmeacr.azurecr.io/acme-catalog:buildpack-1
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 300
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 8080
            timeoutSeconds: 3
          name: catalog
          ports:
          - containerPort: 8080
            name: app-port
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 0
            periodSeconds: 5
            successThreshold: 1
            tcpSocket:
              port: 8080
            timeoutSeconds: 3
          resources:
            limits:
              cpu: "2"
              ephemeral-storage: "5000Mi"
              memory: "4Gi"
            requests:
              cpu: "2"
              ephemeral-storage: "5000Mi"
              memory: "4Gi"
          volumeMounts:
          - mountPath: /tmp
            name: temp
        terminationGracePeriodSeconds: 90
        volumes:
        - emptyDir:
            sizeLimit: "5Gi"
          name: temp
- apiVersion: v1
  kind: Service
  metadata:
    name: catalog
    namespace: default
  spec:
    selector:
      app: catalog
    ports:
      - protocol: TCP
        port: 80
        targetPort: 8080
    type: ClusterIP
