kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: default-user-access
  namespace: default
rules:
- apiGroups: ["", "apps"]
  resources: ["*"]
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: default-user-access
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: default-user-access
subjects:
- kind: Group
  namespace: default
  name: <azure-group-id>