apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.azure.com/tls-cert-keyvault-uri: https://yuwzho-acme-kv.vault.azure.net/certificates/acme-tls
  name: frontend-ingress
  namespace: default
spec:
  ingressClassName: webapprouting.kubernetes.azure.com
  rules:
  - host: frontend.yuwzho-acme.asc-test.net
    http:
      paths:
      - backend:
          service:
            name: frontend
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - frontend.yuwzho-acme.asc-test.net
    # Secret name should be the in patthen "keyvault-<metadata.name>"
    secretName: keyvault-frontend-ingress