apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server-default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: config-server-default
  strategy:
    rollingUpdate:
      maxSurge: 55%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
      labels:
        app: config-server-default
    spec:
      containers:
      - env:
        - name: SPRING_CLOUD_CONFIG_FAILFAST
          value: "true"
        - name: spring.cloud.config.server.git.uri
          value: https://github.com/Azure-Samples/acme-fitness-store-config
        - name: spring.cloud.config.server.git.clone-on-start
          value: "false"
        - name: spring.cloud.config.server.git.skip-ssl-validation
          value: "true"
        - name: spring.cloud.config.server.git.default-label
          value: main
        - name: spring.cloud.config.server.git.ignore-local-ssh-settings
          value: "true"
        - name: spring.profiles.active
          value: test
        image: acmeacr.azurecr.io/config-server:20241107
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 10
          initialDelaySeconds: 30
          periodSeconds: 15
          successThreshold: 1
          tcpSocket:
            port: 8888
          timeoutSeconds: 2
        name: config-server-default
        ports:
        - containerPort: 8888
          protocol: TCP
        readinessProbe:
          failureThreshold: 15
          initialDelaySeconds: 25
          periodSeconds: 3
          successThreshold: 1
          tcpSocket:
            port: 8888
          timeoutSeconds: 2
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 1Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30