apiVersion: v1
data:
  SPRING_CLOUD_CONFIG_FAILFAST: "true"
  SPRING_CLOUD_CONFIG_URI: https://config-server-default.default.svc.cluster.local:8888
kind: ConfigMap
metadata:
  name: config-server-config
  namespace: default
