vector-store:
  file: /src/main/resources/cosmosdb_vector_store.json

spring:
  data:
    mongodb:
      enabled : false
      uri: mongodb://localhost:27017/cosmosdb-vector-store
      database: cosmosdb-vector-store
  ai:
    azure:
      openai:
        chat:
          options:
            deployment-name: gpt-35-turbo-16k
        embedding:
          options:
            deployment-name: text-embedding-ada-002
management:
  endpoints:
    web:
      exposure:
        include: info,health