spring:
  config:
    import: optional:configserver:http://config-server:8888
  cloud:
    config:
      name: catalog
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    encoding: UTF-8
eureka:
  client:
    enabled: false
management:
  endpoints:
    web:
      exposure:
        include: info,health