spring:
  cloud:
    azure:
      cosmos:
        endpoint: ${AZURE_COSMOS_ENDPOINT}
        database: ${AZURE_COSMOS_DATABASE}
eureka:
  client:
    enabled: false
management:
  endpoints:
    web:
      exposure:
        include: info,health